# Generated by Django 5.2.4 on 2025-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='FHIR Patient.name.given', max_length=100)),
                ('last_name', models.CharField(help_text='FHIR Patient.name.family', max_length=100)),
                ('email', models.EmailField(help_text='FHIR Patient.telecom (system=email)', max_length=254)),
                ('phone', models.CharField(help_text='FHIR Patient.telecom (system=phone)', max_length=20)),
                ('date_of_birth', models.DateField(help_text='FHIR Patient.birthDate')),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], default='email', help_text='Preferred contact method (could map to FHIR extension)', max_length=10)),
                ('reason_for_visit', models.TextField(blank=True, help_text='Free text; could be FHIR extension or Annotation')),
                ('consent', models.BooleanField(default=False, help_text='Patient consent for data storage (could be Consent resource later)')),
                ('booking_id', models.CharField(blank=True, help_text='Cal.com ID; future mapping to Appointment.resource.id', max_length=100, null=True)),
                ('booking_datetime', models.DateTimeField(blank=True, help_text='Cal.com booking time; future mapping to Appointment.period.start', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
            ],
        ),
    ]
